version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
    - prealloc
    - unconvert
    - bodyclose
    - nilerr
    - errorlint

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
        - rangeValCopy
    errorlint:
      errorf: false

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
